CREATE TABLE Users(
ID BIGINT PRIMARY KEY AUTO_INCREMENT,
NAME VARCHAR(50) NOT NULL,
SURNAME VARCHAR(50) NOT NULL,
EMAILADDRESS VARCHAR(100) NOT NULL);

CREATE TABLE Accounts(
ID BIGINT PRIMARY KEY AUTO_INCREMENT,
USERNAME VARCHAR(50) NOT NULL,
PASSWORD VARCHAR(50) NOT NULL,
BALANCE DECIMAL(20,2) NOT NULL);

CREATE TABLE Transactions(
ID VARCHAR(1000) PRIMARY KEY,
ACCOUNTTO VARCHAR(50) NOT NULL,
ACCOUNTFROM VARCHAR(50) NOT NULL,
AMOUNT DECIMAL(20,2) NOT NULL)